// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ASPNET_Core_final_project.Data;

#nullable disable

namespace ASPNET_Core_final_project.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221227034432_update")]
    partial class update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("test3.Data.Models.Language", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("test3.Data.Models.Programmer", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateJoin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateLeave")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Programmers");
                });

            modelBuilder.Entity("test3.Data.Models.Programmer_Language", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ProgrammerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("ProgrammerId");

                    b.ToTable("Programmer_Languages");
                });

            modelBuilder.Entity("test3.Data.Models.Programmer_Language", b =>
                {
                    b.HasOne("test3.Data.Models.Language", "Language")
                        .WithMany("Programmer_Language")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("test3.Data.Models.Programmer", "Programmer")
                        .WithMany("Programmer_Language")
                        .HasForeignKey("ProgrammerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Programmer");
                });

            modelBuilder.Entity("test3.Data.Models.Language", b =>
                {
                    b.Navigation("Programmer_Language");
                });

            modelBuilder.Entity("test3.Data.Models.Programmer", b =>
                {
                    b.Navigation("Programmer_Language");
                });
#pragma warning restore 612, 618
        }
    }
}
